apiVersion: v1
kind: Service
metadata:
  name: cricketer-info
spec:
  selector:
    matchLabels: cricketer-info
  replicas:
  template:
    metadata:
      labels:
        app: cricketer-info
    spec:
      containers:
        - name: cricketer-info
          image: cricketer-info:1.0
          imagaPullPolicy: IfNotPresent
          ports:
            - containerPort: 8081